name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm install
      - name: test code
        run : npm test
      - name: build Docker Image
        uses: docker/setup-buildx-action@v1.2.0
        with:
          push: true
          tags: amupxm/pishgoo:latest
